# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-15 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0002_remove_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project',
        ),
    ]
